apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007